export type ApiErrorKind =
	| "network"
	| "timeout"
	| "aborted"
	| "unauthorized"
	| "forbidden"
	| "not-found"
	| "conflict"
	| "validation"
	| "bad-request"
	| "too-many-requests"
	| "server"
	| "unknown";

export type ApiError = {
	kind: ApiErrorKind;
	status?: number;
	message: string;
	code?: string;
	details?: unknown;
};

export type AuthTokens = {
	access_token: string;
	refresh_token: string;
	token_type: string;
	expires_in_seconds: number;
};

export type RegisterRequest = {
	username: string;
	display_name: string;
	email: string;
	/// SRP salt (base64 encoded) - generated by client
	srp_salt: string;
	/// SRP verifier (base64 encoded) - computed by client
	srp_verifier: string;
	date_of_birth: string;
	locale: string;
};

export type AuthUserResponse = {
	id: number;
	username: string;
	display_name: string;
	email: string;
	email_verified?: boolean;
	two_factor_enabled?: boolean;
	avatar_url?: string | null;
	profile_image_url?: string | null;
	profile_picture_url?: string | null;
	profile_picture?: string | null;
	image_url?: string | null;
	photo_url?: string | null;
	avatarUrl?: string | null;
	profilePictureUrl?: string | null;
	avatar?: string | null;
	account_status: string;
	token_version: number;
	created_at: string;
};

export type StatusResponse = {
	status: string;
};

export type EmailVerificationRequest = {
	email: string;
};

export type EmailVerificationConfirmRequest = {
	email: string;
	code: string;
};

/// SRP Challenge Request (Step 1 of login)
export type LoginChallengeRequest = {
	email: string;
};

/// SRP Challenge Response (Step 1 response)
export type LoginChallengeResponse = {
	challenge_id: string;
	srp_salt: string;
	server_public_key_b: string;
};

/// SRP Verify Request (Step 2 of login)
export type LoginVerifyRequest = {
	email: string;
	/// Client public key A (base64 encoded)
	client_public_key_a: string;
	/// Client proof M1 (base64 encoded)
	client_proof_m1: string;
	totp_code?: string;
	backup_code?: string;
};

/// SRP Verify Response (Step 2 response)
export type LoginVerifyResponse = {
	server_proof_m2: string;
	access_token: string;
	refresh_token: string;
	token_type: string;
	expires_in_seconds: number;
};

/// Legacy login request - kept for backward compatibility
export type LoginRequest = {
	email: string;
	password: string;
};

export type RefreshRequest = {
	refresh_token: string;
};

export type ServerDto = {
	id: number;
	owner_user_id: number;
	name: string;
	slug: string;
	description?: string | null;
	icon_url?: string | null;
	is_public: boolean;
	created_at: string;
	updated_at: string;
};

export type ChannelDto = {
	id: number;
	server_id: number;
	name: string;
	topic?: string | null;
	channel_type: string;
	position: number;
	is_private: boolean;
	created_at: string;
	updated_at: string;
};

export type MessageDto = {
	id: number;
	channel_id: number;
	author_user_id: number;
	author_avatar_url?: string | null;
	content: string;
	is_encrypted: boolean;
	ciphertext?: string | null;
	nonce?: string | null;
	aad?: string | null;
	algorithm?: string | null;
	edited_at?: string | null;
	deleted_at?: string | null;
	created_at: string;
	updated_at: string;
};

export type DmThreadDto = {
	id: number;
	peer_user_id: number;
	peer_username: string;
	peer_display_name: string;
	peer_avatar_url?: string | null;
	last_message_preview?: string | null;
	last_message_at?: string | null;
	created_at: string;
	updated_at: string;
};

export type DmMessageDto = {
	id: number;
	thread_id: number;
	author_user_id: number;
	author_avatar_url?: string | null;
	content: string;
	is_encrypted: boolean;
	ciphertext?: string | null;
	nonce?: string | null;
	aad?: string | null;
	algorithm?: string | null;
	edited_at?: string | null;
	deleted_at?: string | null;
	created_at: string;
	updated_at: string;
};

export type PresenceEvent = {
	event_type: string;
	user_id?: number;
	channel?: string;
	payload: Record<string, unknown>;
	ts: number;
};

export type RealtimeConnectionState =
	| "idle"
	| "connecting"
	| "connected"
	| "reconnecting"
	| "disconnected"
	| "error";

export type CreateServerRequestDto = {
	name: string;
	slug: string;
	owner_user_id: number;
	description?: string;
	icon_url?: string;
	is_public?: boolean;
};

export type CreateChannelRequestDto = {
	server_id: number;
	actor_user_id: number;
	name: string;
	topic?: string;
	channel_type?: "text" | "voice" | "announcement";
	position?: number;
	is_private?: boolean;
};

export type CreateMessageRequestDto = {
	channel_id: number;
	author_user_id: number;
	content?: string;
	ciphertext?: string;
	nonce?: string;
	aad?: string;
	algorithm?: string;
	recipient_key_boxes?: Array<{
		recipient_user_id: number;
		encrypted_message_key: string;
		one_time_prekey_id?: number;
	}>;
};

export type CreateDmThreadRequestDto = {
	peer_user_id: number;
};

export type CreateDmMessageRequestDto = {
	content?: string;
	ciphertext?: string;
	nonce?: string;
	aad?: string;
	algorithm?: string;
};

export type FriendRequestStatus = "pending" | "accepted" | "declined";

export type FriendRequestDto = {
	id: number;
	from_user_id: number;
	from_username: string;
	from_display_name: string;
	from_avatar_url?: string | null;
	to_user_id: number;
	to_username: string;
	to_display_name: string;
	status: FriendRequestStatus;
	created_at: string;
	updated_at: string;
};

export type FriendDto = {
	id: number;
	user_id: number;
	friend_user_id: number;
	friend_username: string;
	friend_display_name: string;
	friend_avatar_url?: string | null;
	created_at: string;
};

export type SendFriendRequestDto = {
	username: string;
};

export type E2eePublicBundle = {
	user_id: number;
	identity_key: string;
	signed_prekey_id: number;
	signed_prekey: string;
	signed_prekey_signature: string;
};

export type E2eeClaimedBundle = E2eePublicBundle & {
	one_time_prekey_id: number;
	one_time_prekey: string;
};
